#!/usr/bin/env python3

import os
import sys
import helpers

from analyzer import Analyzer
from termcolor import colored

def main():
    if len(sys.argv) != 2:
        print("Usage: ./tweets @screen_name")
        return 1
    username = sys.argv[1]
    
    positives = os.path.join(sys.path[0], "positive-words.txt")
    negatives = os.path.join(sys.path[0], "negative-words.txt")
    analyzer = Analyzer(positives, negatives)
    
    tweets = helpers.get_user_timeline(username, 50)
    for tweet in tweets:
        score = analyzer.analyze(tweet)
        color = ""
        if score > 0.0:
            color = "green"
        elif score < 0.0:
            color = "red"
        else:
            color = "yellow"
    
        print(score, colored(tweet, color))
        
    
    return 0

if __name__ == "__main__":
    ret = main()
    exit(ret)